name: 'Publish GitHub Action with ncc'
description: 'Publish your GitHub Action with ncc'
author: 'joshjohanning'
branding:
  icon: 'package'
  color: 'black'
inputs:
  github_token:
    description: 'Token for the github API'
    required: true
  github_api_url:
    description: 'GitHub API URL (e.g., https://api.github.com for GitHub.com or https://ghes.domain.com/api/v3 for GHES)'
    required: false
    default: '${{ github.api_url }}'
  npm_package_command:
    description: 'Command to build the action'
    default: 'npm run package'
    required: false
  commit_node_modules:
    description: 'Change to true to commit node_modules folder'
    default: 'false'
    required: false
  commit_dist_folder:
    description: 'Change to true to commit dist folder'
    default: 'true'
    required: false
  publish_minor_version:
    description: 'Change to true to publish minor version'
    default: 'false'
    required: false
  publish_release_branch:
    description: 'Change to true to publish release branch'
    default: 'false'
    required: false
  create_release_as_draft:
    description: 'Change to true to create release as draft'
    default: 'false'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
