name: "Publish GitHub Action"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - uses: tgymnich/publish-github-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
